#
# Makefile -- Separation
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
all:	partdiff-handout-5.pdf partdiff-presentation-5.pdf

partdiff-handout-5.pdf:	partdiff-handout-5.tex slides.tex
	pdflatex partdiff-handout-5.tex

partdiff-presentation-5.pdf:	partdiff-presentation-5.tex slides.tex
	pdflatex partdiff-presentation-5.tex
