#
# Makefile -- Separation
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
FILES = slides.tex common.tex
all:	partdiff-handout-5.pdf partdiff-presentation-5.pdf

partdiff-handout-5.pdf:	partdiff-handout-5.tex $(FILES)
	pdflatex partdiff-handout-5.tex

partdiff-presentation-5.pdf:	partdiff-presentation-5.tex $(FILES)
	pdflatex partdiff-presentation-5.tex
