#
# Makefile -- images for chapte r9
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	hyperbolic.pdf parabolic.pdf ql.pdf elliptic.pdf

elliptic.pdf:	elliptic.tex
	pdflatex elliptic.tex

hyperbolic.pdf:	hyperbolic.tex
	pdflatex hyperbolic.tex

parabolic.pdf:	parabolic.tex
	pdflatex parabolic.tex

ql.pdf:	ql.tex
	pdflatex ql.tex
