#
# Makefile -- images for chapte r9
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	exponential.pdf wavechar.pdf dxdy.pdf \
	hyperbolic.pdf parabolic.pdf ql.pdf elliptic.pdf

elliptic.pdf:	elliptic.tex
	pdflatex elliptic.tex

hyperbolic.pdf:	hyperbolic.tex
	pdflatex hyperbolic.tex

parabolic.pdf:	parabolic.tex
	pdflatex parabolic.tex

ql.pdf:	ql.tex
	pdflatex ql.tex

dxdy.pdf:	dxdy.tex
	pdflatex dxdy.tex

wavechar.pdf:	wavechar.tex
	pdflatex wavechar.tex

exponential.pdf:	exponential.tex
	pdflatex exponential.tex
