#
# Makefile -- Separation
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
all:	partdiff-handout-4.pdf partdiff-presentation-4.pdf

partdiff-handout-4.pdf:	partdiff-handout-4.tex slides.tex
	pdflatex partdiff-handout-4.tex

partdiff-presentation-4.pdf:	partdiff-presentation-4.tex slides.tex
	pdflatex partdiff-presentation-4.tex
