#
# Makefile -- Separation
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
TEXFILES = slides.tex common.tex

all:	partdiff-handout-4.pdf partdiff-presentation-4.pdf

partdiff-handout-4.pdf:	partdiff-handout-4.tex $(TEXFILES)
	pdflatex partdiff-handout-4.tex

partdiff-presentation-4.pdf:	partdiff-presentation-4.tex $(TEXFILES)
	pdflatex partdiff-presentation-4.tex
