#
# Makefile -- build images for chapter 2
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	disk.pdf oblique.pdf domain.pdf wave.pdf mismatch.pdf

disk.pdf:	disk.tex
	pdflatex disk.tex

oblique.pdf:	oblique.tex
	pdflatex oblique.tex

domain.pdf:	domain.tex
	pdflatex domain.tex

wave.pdf:	wave.tex
	pdflatex wave.tex

mismatch.pdf:	mismatch.tex
	pdflatex mismatch.tex
