#
# Makefile -- Separation
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
all:	partdiff-handout-3.pdf partdiff-presentation-3.pdf

partdiff-handout-3.pdf:	partdiff-handout-3.tex slides.tex
	pdflatex partdiff-handout-3.tex

partdiff-presentation-3.pdf:	partdiff-presentation-3.tex slides.tex
	pdflatex partdiff-presentation-3.tex
