#
# Makefile -- Separation
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
TEXFILES = slides.tex common.tex

all:	partdiff-handout-3.pdf partdiff-presentation-3.pdf

partdiff-handout-3.pdf:	partdiff-handout-3.tex $(TEXFILES)
	pdflatex partdiff-handout-3.tex

partdiff-presentation-3.pdf:	partdiff-presentation-3.tex $(TEXFILES)
	pdflatex partdiff-presentation-3.tex
