#
# Makefile -- Skript in Kapitel unterteilen
#
# (c) 2016 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
parts =	skript-01-intro.pdf		\
	skript-02-chapter1.pdf		\
	skript-03-chapter2.pdf		\
	skript-04-chapter3.pdf		\
	skript-05-chapter4.pdf		\
	skript-06-chapter5.pdf		\
	skript-07-chapter6.pdf		\
	skript-08-chapter7.pdf		\
	skript-09-chapter8.pdf		\
	skript-10-chapter9.pdf		\
	skript-11-appendixa.pdf		\
	skript-12-index.pdf

parts:	$(parts)

skript-01-intro.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-01-intro.pdf ../skript.pdf 1-10

skript-02-chapter1.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-02-chapter1.pdf ../skript.pdf 11-18

skript-03-chapter2.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-03-chapter2.pdf ../skript.pdf 19-36

skript-04-chapter3.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-04-chapter3.pdf ../skript.pdf 37-54

skript-05-chapter4.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-05-chapter4.pdf ../skript.pdf 55-84

skript-06-chapter5.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-06-chapter5.pdf ../skript.pdf 85-94

skript-07-chapter6.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-07-chapter6.pdf ../skript.pdf 95-102

skript-08-chapter7.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-08-chapter7.pdf ../skript.pdf 103-122

skript-09-chapter8.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-09-chapter8.pdf ../skript.pdf 123-130

skript-10-chapter9.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-10-chapter9.pdf ../skript.pdf 131-152

skript-11-appendixa.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-11-appendixa.pdf ../skript.pdf 153-158

skript-12-index.pdf:	../skript.pdf Makefile
	pdfjam --outfile skript-12-index.pdf ../skript.pdf 159-160
