#
# Makefile -- Separation
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
FILES = slides.tex common.tex

all:	partdiff-handout-6.pdf partdiff-presentation-6.pdf

partdiff-handout-6.pdf:	partdiff-handout-6.tex $(FILES)
	pdflatex partdiff-handout-6.tex

partdiff-presentation-6.pdf:	partdiff-presentation-6.tex $(FILES)
	pdflatex partdiff-presentation-6.tex
