#
# Makefile -- Separation
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
all:	partdiff-handout-6.pdf partdiff-presentation-6.pdf

partdiff-handout-6.pdf:	partdiff-handout-6.tex slides.tex
	pdflatex partdiff-handout-6.tex

partdiff-presentation-6.pdf:	partdiff-presentation-6.tex slides.tex
	pdflatex partdiff-presentation-6.tex
