#
# Makefile -- build images for chapter 3
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	circular.pdf rays.pdf

circular.pdf:	circular.tex
	pdflatex circular.tex

rays.pdf:	rays.tex
	pdflatex rays.tex

