//
// parameters.inc
//
// (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
//

#declare dxfactor = 1;
#declare dyfactor = 1;

#declare xgridspacing = 0.2;
#declare ygridspacing = 0.2;

#declare nsteps = 20;

#declare xmin = 0.0;
#declare xmax = 3.2;

#declare ymin = 0.0;
#declare ymax = 3.2;

//#declare show_grid = true;
//#declare show_surface = true;
//#declare show_normal = false;
//#declare show_tangent = false;
//#declare show_red = false;
//#declare show_legs = false;
//#declare show_lines = false;
//#declare show_steps = false;
